# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'project1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'

  # Pods for project1

  target 'project1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'project1UITests' do
    # Pods for testing
  end

end
